package com.edusphere.curriculum.controller;

import com.edusphere.common.dto.ApiResponse;
import com.edusphere.curriculum.dto.GeneratePlanRequest;
import com.edusphere.curriculum.dto.LearningPlanDto;
import com.edusphere.curriculum.service.LearningPlanService;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/curriculum")
@RequiredArgsConstructor
public class CurriculumController {

    private final LearningPlanService service;

    @PostMapping("/plans/generate")
    public ApiResponse<LearningPlanDto> generate(@RequestBody GeneratePlanRequest request) {
        return ApiResponse.ok("Plan generated by AI", service.generatePlan(request));
    }

    @GetMapping("/plans/{id}")
    public ApiResponse<LearningPlanDto> getPlan(@PathVariable UUID id) {
        return ApiResponse.ok(service.getById(id));
    }

    @GetMapping("/plans/student/{studentId}")
    public ApiResponse<List<LearningPlanDto>> getStudentPlans(@PathVariable UUID studentId) {
        return ApiResponse.ok(service.getByStudent(studentId));
    }

    @PutMapping("/plans/{id}/approve")
    public ApiResponse<LearningPlanDto> approve(
            @PathVariable UUID id,
            @RequestParam UUID teacherId,
            @RequestBody(required = false) LearningPlanDto updates) {
        return ApiResponse.ok("Plan approved", service.approveByTeacher(id, teacherId, updates != null ? updates : new LearningPlanDto()));
    }

    @PutMapping("/plans/{id}")
    public ApiResponse<LearningPlanDto> update(@PathVariable UUID id, @RequestBody LearningPlanDto dto) {
        dto.setId(id);
        return ApiResponse.ok(service.save(dto));
    }
}
